### ISSUE TITLE
Design proposal (messages and encoders/decoders)

### ISSUE THREAD

**Issue by domire8** [aica-technology/network-interfaces#35]
The goal of this issue is to discuss [this document](https://docs.google.com/document/d/1eC-Az133LvQBftsMc_UXm5GkeQV6wAoXFCAzXOkPLWk/edit#) containing an overview of the desired structure of the new communication interfaces. In particular, we need to answer the question of which common message types we support and what type of custom messages we want to add here.

**Comment by domire8** [comment]
As per my discussion with @LouisBrunner:
In general, it would be nice if network interfaces doesn't depend on state representation or vice versa. To achieve that,
1. `ISocket` should not inherit from `ParameterMap`. Instead, derived classes should set all parameters in the constructor (with the help of structs)
2. `ByteArray` could be replaced with a simple `std::string`. This would allow definitions of `decode` and `encode` in any part of the stack without being dependent on network interfaces

**Comment by eeberhard** [comment]
I agree with this and think it's absolutely a good idea to put the basic message structures (e.g. RobotState and RobotCommand) in protobuf as well.
