### ISSUE TITLE
Link cppzmq correctly in communication interfaces

### ISSUE THREAD

**Issue by domire8** [aica-technology/network-interfaces#46]
Currently, packages depending on communication interfaces need to link `cppzmq` manually, which is not optimal. This should somehow happen automatically

**Comment by domire8** [comment]
I created a branch to this issue: https://github.com/aica-technology/network-interfaces/tree/fix/linking
Running the `dev-server.sh` script under source currently fails at the linking state of an executable that links `communication_interfaces` but not `cppzmq`. If `cppzmq` is linked however, it succeeds.

@LouisBrunner FYI. This is not an urgent matter. But I have little faith i can solve it on my own :smile:

**Comment by LouisBrunner** [comment]
> I created a branch to this issue: https://github.com/aica-technology/network-interfaces/tree/fix/linking Running the `dev-server.sh` script under source currently fails at the linking state of an executable that links `communication_interfaces` but not `cppzmq`. If `cppzmq` is linked however, it succeeds.
> 
> @LouisBrunner FYI. This is not an urgent matter. But I have little faith i can solve it on my own 😄

Will take a look 😄

**Comment by LouisBrunner** [comment]
@domire8 I just pushed a commit on your branch (https://github.com/aica-technology/network-interfaces/commit/5312fd4fcab81df1a22b2468e8784882e1de09c7) which makes the dependent find their dependencies (including transitive ones) automatically. 😃

**Comment by domire8** [comment]
Ouh yeah nice, thanks a lot!
