### ISSUE TITLE
Notify if open() has not been called

### ISSUE THREAD

**Issue by domire8** [aica-technology/network-interfaces#65]
A user may forget to call `socket.open()` and then try to send/receive messages. In Python, this gives a segmentation fault. It could be nice to add a check `is_open` in send/receive and throw a corresponding error in case.

**Comment by domire8** [comment]
My suggestion would be the following:
- In `ISocket.hpp`: renaming but keeping them pure virtual
  - `open()` --> `on_open()`
  - `receive_bytes(...)` --> `on_receive(...)`
  - `send_bytes(...)` --> `on_send(...)`
- Add `open()` that does
```cpp
void open() {
  try {  on_open(); this->opened_ = true; } catch (...) {}
}
```
- Add back `receive_bytes(...)` that does
```
bool receive_bytes(std::string) {
  if (!this->opened_) { return false; }
  return this->on_receive(std::string);
}
```

And then same for send.
What do you think @eeberhard ?`

**Comment by eeberhard** [comment]
It reminds me of a discussion we had a while ago, I think around `configure`, where we touched on the idea of the virtual wrapper functions to do additional things the base class. In any case I think your proposed pattern provides a bit more flexibility in the implementation while keeping things simple and consistent for the user.
