### ISSUE TITLE
Add examples for handling strings and bytes with python bindings

### ISSUE THREAD

**Issue by domire8** [aica-technology/network-interfaces#67]
As proposed in #66, it would be nice to clarify the usage of the Python bindings regarding the reception and sending of bytes vs strings.

An example snippet could go into the README

**Comment by JasperTan97** [comment]
So I am trying to understand what you mean here, but when I do:
```python
    str_msg = "HELLO!"
    server.send_bytes(str_msg.rstrip("\x00"))
    str_msg = client.receive_bytes()
    print(str_msg)
    time.sleep(0.4)
```
I get `b'HELLO!'` instead of `HELLO!` as I expected. The additional `b'` and `'` is the issue in question? And that the user should strip away these additional characters that get added when converting c++ strings into python?

**Comment by domire8** [comment]
You can have a look at the tests, it is indeed expected that you get `b'HELLO!'` back. As discussed in #66, it's the responsibility of the receiver to decode and sanitize the bytes

**Comment by domire8** [comment]
Yeah, the goal is just to provide a code snippet that shows how to use this library.
At the beginning, I thought that if you do `send_bytes("hello")` then the return value of `receive_bytes()` should be `"hello"`. However there is no easy and general solution that would enable this so it would be good to say in the README that the user can't expect that and has to decode and strip the return value of receive him/herself
