### ISSUE TITLE
Release 2.1

### ISSUE THREAD

**Issue by domire8** [aica-technology/network-interfaces#72]
After https://github.com/aica-technology/control-libraries/issues/159

**Comment by domire8** [comment]
So this is a bit of a mess at this point. The library `communication_interfaces` is at version 1.0.1, the repo/production image is at 2.0.1...

So I'd probably have to set version 2.0.0 for the library itself (since #68 was technically breaking) and then tag the repo with 3.0.0 (since #69 and #71 changed the production image)..?

**Comment by LouisBrunner** [comment]
Is it worth bumping the library to `3.0.0` as well so they are in sync?

**Comment by domire8** [comment]
We could but it will be the last release in this repo anyway, then it goes into control libraries with the control libraries version

**Comment by domire8** [comment]
v2.0.2 was released and from now on, control-libraries v8.1.0 or v9.0.0 can be used
